config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "top#index"
  resources :top, only: :index
  resources :videos
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  validates :title, :youtuber_name, :url, :detail, presence: true
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @videos = @user.videos
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.includes(:user)
  end

  def new
    @video =Video.new
  end

  def create
    Video.create(video_params)
    redirect_to videos_path
  end

  def show
    @video = Video.find(params[:id])
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    video = Video.find(params[:id])
    video.update(video_params)
    redirect_to video_path(video.id)
  end

  def destroy
    video = Video.find(params[:id])
    video.destroy
    redirect_to videos_path
  end

  private
  def video_params
    params.require(:video).permit(:title, :youtuber_name, :url, :detail).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Yourevi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .wrapper
      = render "shared/header"
    = yield

app/views/shared/_header.html.haml
.header
  %ul.header__title-lists
    %li.title-list
      = link_to '/', class: "home-link" do
        = icon('fab', 'youtube',class: 'youtube-icon')
        %p.title
          YOUREVI
    %li.title-list
      %h3.sub-title
        \- ユーレビ -

  %ul.header__lists
    %li.list
      = link_to new_video_path, class: "header__right--btn" do
        プレゼンする
    %li.list
      = link_to videos_path, class: "header__right--btn" do
        投稿一覧
    - if user_signed_in?
      %li.list
        = link_to current_user.user_name, user_path(current_user), class: "header__right--btn"
      %li.list
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn"
    - else
      %li.list
        = link_to "ログイン", new_user_session_path, class: "header__right--btn"

app/views/shared/_videos.html.haml
.content
  .content__left
    .content__left--image
  .content__right
    .content__right__top
      = link_to video.title, video_path(video.id), class: "content__right__top--title"
    .content__right__bottom
      = video.youtuber_name
      = video.detail
      .content__right__bottom--userName
        = link_to video.user.user_name, user_path(video.user), class: "content__right__bottom--userName--btn"
      .content__right__bottom--date
        = video.url
        = video.created_at

app/views/top/index.html.haml
.wrapper
  = render "shared/header"
.contents
  #home.big-bg
    .home-content
      %h2.page-title Support your passion
      %p.page-sub-title あなたを支えるYouTubeクリエイターをプレゼンしませんか？ YouTuber応援コミュニティ。
      %a.button{href: new_video_path} プレゼンする

app/views/users/show.html.haml
.row
  .videoTitle
    = @user.user_name
    さんの投稿一覧
  - @videos.each do |video|
    = render partial: "shared/videos", locals: { video: video }

app/views/videos/edit.html.haml
.row
  .content-title
    新規でプレゼンする
  = form_with model: @video, class: "form", local: true do |f|
    = f.text_field :title, placeholder: :タイトル, class: "form-contents"
    = f.text_field :youtuber_name, placeholder: :"Youtuberの名前", class: "form-youtuber"
    = f.text_field :url, placeholder: :オススメ動画のURL, class: "form-contents"
    = f.text_area :detail, placeholder: :プレゼン内容を入力してください！, class: "form-detail"
    = f.submit '投稿する', class: "form-btn"

app/views/videos/index.html.haml
.wrapper
  = render "shared/header"
.row
  - @videos.each do |video|
    .content
      .content__left
        .content__left--image
      .content__right
        .content__right__top
          = link_to video.title, video_path(video.id), class: "content__right__top--title"
        .content__right__bottom
          = video.youtuber_name
          = video.detail
          .content__right__bottom--userName
            = video.user.user_name
          .content__right__bottom--date
            =video.url
            -# = video.created_at

app/views/videos/new.html.haml
.row
  .content-title
    新規でプレゼンする
  = form_with model: @video, class: "form", local: true do |f|
    = f.text_field :title, placeholder: :タイトル, class: "form-contents"
    = f.text_field :youtuber_name, placeholder: :"Youtuberの名前", class: "form-youtuber"
    = f.text_field :url, placeholder: :オススメ動画のURL, class: "form-contents"
    = f.text_area :detail, placeholder: :プレゼン内容を入力してください！, class: "form-detail"
    = f.submit '投稿する', class: "form-btn"

app/views/videos/show.html.haml
.row
  .videoTitle
    = @video.title
  .videoDate
    = @video.url
    %br/
    = @video.youtuber_name
  .videoAuthor
  .videoText
    = simple_format @video.detail
  - if user_signed_in? && current_user.id == @video.user_id
    .videoManage
    = link_to "編集", edit_video_path(@video.id), class: "videoManage__edit"
    = link_to "削除", video_path(@video.id), method: :delete, class: "videoManage__delete"